version: '3'
services: 
  api:
    depends_on:
      - db
    build: 
      context: ./api
    volumes:
      - ./api/src:/go/sec
    ports: 
      - 8080:8080
    environment:
      - "GOPATH=/go"
    platform: linux/amd64

  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: myjchatapp
    ports:
      - 3306:3306